name: vzyle
favicon: null
layout_spectrum: 0.1872437964193523
typography_spectrum: 0.4426461630500853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1875
  lightness: 0.2947943755425513
  saturation: 0.7499038353562355
  rhythmicContrast: 0.03194074355997145
purpose: []
